import React, { useEffect, useState } from "react";
import { useLocation, Link } from "react-router-dom";
import "./ResultPage.css";

export default function ResultPage() {
    const location = useLocation();
    const state = location.state;
    const [afterImgLoaded, setAfterImgLoaded] = useState(false);
    const [afterImgError, setAfterImgError] = useState(false);

    useEffect(() => {
        if (!state?.afterSmileUrl) {
            window.location.href = "/";
        }
    }, [state]);

    if (!state?.afterSmileUrl) return null;

    const { name, treatments, analysisSummary, afterSmileUrl, originalImageUrl } = state;

    function handleDownload() {
        const link = document.createElement("a");
        link.href = afterSmileUrl;
        link.target = "_blank";
        link.rel = "noopener noreferrer";
        link.click();
    }

    function handleDownloadPDF() {
        const printWindow = window.open('', '_blank', 'width=800,height=900');
        if (!printWindow) return;

        const htmlContent = `
            <!DOCTYPE html>
            <html>
                <head>
                    <title>${name ? name.split(" ")[0] + "'s" : "Your"} Treatment Plan</title>
                    <style>
                        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; padding: 40px; line-height: 1.6; max-width: 800px; margin: 0 auto; }
                        h1 { color: #1a1a1a; border-bottom: 2px solid #0eb39e; padding-bottom: 12px; margin-bottom: 30px; font-weight: normal; }
                        h2 { color: #0eb39e; margin-top: 40px; font-weight: normal; }
                        .summary { background: #f9f9f9; padding: 24px; border-left: 4px solid #0eb39e; border-radius: 4px; font-size: 1.05em; }
                        .list { list-style: none; padding: 0; margin-top: 24px; }
                        .list-item { margin-bottom: 16px; padding: 16px; background: #fff; border: 1px solid #eaeaea; border-radius: 6px; display: flex; align-items: center; gap: 16px; font-size: 1.05em; }
                        .num { background: #0eb39e; color: #fff; padding: 6px 12px; border-radius: 4px; font-weight: bold; font-size: 0.9em; }
                        .footer { margin-top: 60px; font-size: 0.85em; color: #777; text-align: center; border-top: 1px solid #eaeaea; padding-top: 20px; }
                    </style>
                </head>
                <body>
                    <h1>${name ? name.split(" ")[0] + "'s" : "Your"} Clinical Treatment Plan</h1>
                    
                    <h2>Clinical Insights</h2>
                    <div class="summary">${analysisSummary}</div>

                    <h2>Selected Blueprint</h2>
                    <ul class="list">
                        ${treatments.map((t, i) => `
                            <li class="list-item">
                                <span class="num">${String(i + 1).padStart(2, "0")}</span>
                                <span>${t}</span>
                            </li>
                        `).join('')}
                    </ul>

                    <div class="footer">
                        Generated by Smile Preview.<br/>
                        This document acts as a conceptual preview. Consult with a licensed professional for formal diagnosis and results.
                    </div>
                </body>
                <script>
                    window.onload = function() { 
                        setTimeout(function(){
                            window.print(); 
                            window.close();
                        }, 500);
                    }
                </script>
            </html>
        `;

        printWindow.document.open();
        printWindow.document.write(htmlContent);
        printWindow.document.close();
    }

    return (
        <main className="result-page">
            <div className="result-header">
                <div className="result-header__badge">
                    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                        <polyline points="20 6 9 17 4 12" />
                    </svg>
                    Assessment Complete
                </div>
                <h1 className="result-header__title">
                    {name ? `${name.split(" ")[0]}'s` : "Your"}{" "}
                    <span className="gradient-text">New Look</span>
                </h1>
                <p className="result-header__desc">
                    Review your simulated outcome below, meticulously mapped based on your selected structural focus.
                </p>
            </div>

            <div className="comparison-wrap">
                <div className="comparison-card glass-card">
                    <div className="comparison-label comparison-label--before">Original</div>
                    <img
                        src={originalImageUrl}
                        alt="Before treatment"
                        className="comparison-img"
                    />
                    <div className="comparison-footer">
                        <span>Baseline Assessment</span>
                    </div>
                </div>

                <div className="comparison-arrow">
                    <div className="arrow-line" />
                    <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M5 12h14M12 5l7 7-7 7" stroke="var(--accent)" />
                    </svg>
                    <div className="arrow-line" />
                </div>

                <div className="comparison-card comparison-card--after glass-card">
                    <div className="comparison-label comparison-label--after">Simulated</div>
                    {afterImgError ? (
                        <div className="comparison-img comparison-img--placeholder" style={{ display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: "12px", color: "var(--text-muted)", fontSize: "0.9rem" }}>
                            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                                <circle cx="12" cy="12" r="10"/>
                                <line x1="12" y1="8" x2="12" y2="12"/>
                                <line x1="12" y1="16" x2="12.01" y2="16"/>
                            </svg>
                            <span>Processing delay...</span>
                            <a href={afterSmileUrl} target="_blank" rel="noopener noreferrer" className="btn btn--ghost btn--sm" style={{ marginTop: "8px" }}>Force Open</a>
                        </div>
                    ) : (
                        <>
                            {!afterImgLoaded && (
                                <div className="comparison-img comparison-img--skeleton" />
                            )}
                            <img
                                src={afterSmileUrl}
                                alt="After treatment"
                                className="comparison-img"
                                style={{ display: afterImgLoaded ? "block" : "none" }}
                                onLoad={() => setAfterImgLoaded(true)}
                                onError={() => setAfterImgError(true)}
                            />
                        </>
                    )}
                    <div className="comparison-footer comparison-footer--after">
                        <span>{afterImgLoaded ? "Simulated Projection" : "Rendering image..."}</span>
                    </div>
                </div>

            </div>

            <div className="result-details">
                <div className="result-summary glass-card">
                    <h3 className="result-block__title">
                        Clinical Insights
                    </h3>
                    <p className="result-summary__text">{analysisSummary}</p>
                </div>

                <div className="result-treatments glass-card">
                    <h3 className="result-block__title">
                        Selected Blueprint
                    </h3>
                    <ul className="result-treatment-list">
                        {treatments.map((t, i) => (
                            <li key={t} className="result-treatment-item">
                                <span className="result-treatment-num">{String(i + 1).padStart(2, "0")}</span>
                                <span>{t}</span>
                            </li>
                        ))}
                    </ul>
                </div>
            </div>

            <div className="result-cta glass-card">
                <div className="result-cta__text">
                    <h3>Explore Your Options</h3>
                    <p>A specialized consultant will be in touch shortly to discuss your custom plan.</p>
                </div>
                <div className="result-cta__actions">
                    <button className="btn btn--primary" onClick={handleDownload}>
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                            <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" />
                        </svg>
                        Save Portfolio
                    </button>
                    <button className="btn btn--ghost" onClick={handleDownloadPDF} style={{ border: '1px solid var(--border-strong)', background: 'var(--bg-primary)' }}>
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" style={{ marginRight: '8px' }}>
                            <path d="M14 2H6a2 2 0 0 0-2 2v16c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V8l-6-6z" />
                            <path d="M14 3v5h5M16 13H8M16 17H8M10 9H8" />
                        </svg>
                        Download PDF Plan
                    </button>
                    <Link to="/analyze" className="btn btn--ghost">
                        Start Over
                    </Link>
                    <Link to="/" className="btn btn--ghost">
                        Home
                    </Link>
                </div>
            </div>

            <p className="result-disclaimer">
                Note: This simulation acts as a conceptual preview. Consult with a licensed professional for formal diagnosis and results.
            </p>
        </main>
    );
}
